### ISSUE TITLE
Parameters do not return anything besides connecting to

### ISSUE THREAD

**Issue by zjorz** [SygniaLabs/BackupKeyManager#3]
Both ....
* BackupKeyManager.exe GetBackupKey
* BackupKeyManager.exe Validate

... do not return anything besides:
[-] Setting up connection with Domain Controller:

For example "BackupKeyManager.exe GetPublicKey" does provide data, so does "BackupKeyManager.exe GenerateNewBackupKey" appears to work correctly

OUTPUT:
========================================
D:\Support-Stuff\Tools\DPAPIBackupKeyManager\x64\Release>BackupKeyManager.exe Validate -s R0FSRWDC1.ADTEC.NET

[-] Setting up connection with Domain Controller: R0FSRWDC1.ADTEC.NET

D:\Support-Stuff\Tools\DPAPIBackupKeyManager\x64\Release>
========================================
D:\Support-Stuff\Tools\DPAPIBackupKeyManager\x64\Release>BackupKeyManager.exe GetBackupKey -s R0FSRWDC1.ADTEC.NET

[-] Setting up connection with Domain Controller: R0FSRWDC1.ADTEC.NET

D:\Support-Stuff\Tools\DPAPIBackupKeyManager\x64\Release>
========================================
D:\Support-Stuff\Tools\DPAPIBackupKeyManager\x64\Release>BackupKeyManager.exe GetPublicKey -s R0FSRWDC1.ADTEC.NET

[-] Setting up connection with Domain Controller: R0FSRWDC1.ADTEC.NET
[-] Retrieving the current BackupKey public certificate via MS-BKRP...OK -> Certificate size: 744
[+] MS-BKRP Serviced Backupkey Guid         : a2a67715-f5cd-4a35-8bbc-09ea9ac89ce2

[+] Operation completed successfully!

D:\Support-Stuff\Tools\DPAPIBackupKeyManager\x64\Release>
========================================

**Comment by Alef-Burzmali** [comment]
Hello,

This seems to be due to calling `LSA_UNICODE_STRING.Dispose()` on `lusSecretData`, the `LSA_UNICODE_STRING` parsed from `PrivateData` returned by `Interop.LsaRetrievePrivateData`, on lines  [160-162](https://github.com/SygniaLabs/BackupKeyManager/blob/db64fd9/BackupKeyManager/Program.cs#L160-L162) and on [line 222](https://github.com/SygniaLabs/BackupKeyManager/blob/db64fd9/BackupKeyManager/Program.cs#L222).

SharpDPAPI calls instead `Interop.LsaFreeMemory(PrivateData);` as required by the [documentation](https://learn.microsoft.com/en-us/windows/win32/api/ntsecapi/nf-ntsecapi-lsaretrieveprivatedata#parameters), and does not dispose of the unicode string itself.

I've replace L160-162 by:
```c#
                // lusSecretData.Dispose();
                Interop.LsaFreeMemory(PrivateData);
                secretName.Dispose();
                //Marshal.FreeHGlobal(PrivateData);
```
and L221-222 by:
```c#
                backupKeyLSA.Dispose();
                Interop.LsaFreeMemory(PrivateData);
                //backupKeyBytesLSA.Dispose();
```

**Comment by zjorz** [comment]
@Alef-Burzmali @gilb1 I made the following changes and can confirm my issues have been resolved:

[1]
        // https://github.com/SygniaLabs/BackupKeyManager/issues/4
        //private static readonly int CERT_VALIDITY_PERIOD_YEARS = 1;
        private static readonly int CERT_VALIDITY_PERIOD_DAYS = 365;

[2]
                // https://github.com/SygniaLabs/BackupKeyManager/blob/db64fd9/BackupKeyManager/Program.cs#L160-L162
                // lusSecretData.Dispose();
                Interop.LsaFreeMemory(PrivateData);
                secretName.Dispose();
                //Marshal.FreeHGlobal(PrivateData);

[3]
            // https://github.com/SygniaLabs/BackupKeyManager/issues/4
            //var certificate = certRequest.Create(dn, generator, DateTime.UtcNow, DateTime.UtcNow.AddYears(1), certSerial);
            var certificate = certRequest.Create(dn, generator, DateTime.UtcNow, 
            DateTime.UtcNow.AddDays(CERT_VALIDITY_PERIOD_DAYS), certSerial);

**Comment by B1t0n** [comment]
Thank you guys for raising this issue and for your suggestions.
Changed were made and push to main branch: https://github.com/SygniaLabs/BackupKeyManager/pull/5
