### ISSUE TITLE
Certificate generation and validation fail on leap years

### ISSUE THREAD

**Issue by Alef-Burzmali** [SygniaLabs/BackupKeyManager#4]
Hello,

[MS-BKRP 2.2.1](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-bkrp/db5c89f0-b036-489e-aa68-baa14cc683d3) requires a certificate that is valid for exactly 365 days.

The code is currently inconsistent:
- [CERT_VALIDITY_PERIOD_YEARS](https://github.com/SygniaLabs/BackupKeyManager/blob/db64fd9/BackupKeyManager/Program.cs#L110) is 1 year (potentially 366 days on leap year like 2024)
- [BkpCertInfoValidate](https://github.com/SygniaLabs/BackupKeyManager/blob/db64fd9/BackupKeyManager/Program.cs#L605) uses that constant, but has an error message correctly indicating 365 years.
- [GenerateDPAPIBackupKey](https://github.com/SygniaLabs/BackupKeyManager/blob/db64fd9/BackupKeyManager/Program.cs#L605) is hardcoded to 1 year.

I can confirm that a certificate natively generated by a WS 2022 Domain Controller is exactly 365 days, and not 366 on leap year, and that `BkpCertInfoValidate` incorrectly says that the certificate is invalid:
```
.\BackupKeyManager.exe GetBackupKey --analyze -s dc1.adlab.example.com
[-] Setting up connection with Domain Controller: dc1.adlab.example.com
[-] Getting backup key     : G$BCKUPKEY_df1e4415-[redacted]
[-] BackupKey size: 1956
[-] Validating BackupKey header...
[-] Analyzing certificate information:
[Certificate] Serial Number:     8F-12-6D-2E-[redacted]
[Certificate] Version:           3
[Certificate] Issuer name:       adlab.example.com
[Certificate] Subject name:      adlab.example.com
[Certificate] Not Before:        20/05/2023 22:04:38 +00:00
[Certificate] Not After:         19/05/2024 22:04:38 +00:00
[Certificate] Validity period:   365.00:00:00
[Certificate] SignatureAlgo OID: 1.3.14.3.2.29
[Certificate] PublicKeyInfo OID: 1.2.840.113549.1.1.1
[Certificate] RSA Key Size:      2048 bits
[Certificate] Certificate Guid:  df1e4415-[redacted]

[-] Validating Certificate format...
[!] ERROR: Certificate validity should be 365 days

[+] Operation completed successfully!
```

I would suggest using `CERT_VALIDITY_PERIOD_DAYS = 365` through the code base.

**Comment by B1t0n** [comment]
Thanks for the heads up - changed applied:
https://github.com/SygniaLabs/BackupKeyManager/pull/5
